import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cookieToInitialState } from "wagmi";
import { config } from "@/lib/config/wallet-config";
import { headers } from "next/headers";
import WagmiProviderComp from "@/providers/WagmiProvider";
import { ThemeProvider } from "@/lib/utils/theme-provider";
import Navbar from "@/components/Navbar";
import { RetroGrid } from "@/components/ui/Backgrounds/RetroGrid";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en" className="overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <WagmiProviderComp initialState={initialState}>
            <div className="flex flex-col w-full h-screen">
              {/* Navbar at the top */}
              <Navbar />

              {/* Main content area */}
              <div className="flex  flex-col flex-grow justify-center items-center px-5">
                <div className="flex flex-col h-[80vh] w-full justify-center items-center">
                  {children}
                  <RetroGrid />
                </div>
              </div>
            </div>
          </WagmiProviderComp>
        </ThemeProvider>
      </body>
    </html>
  );
}
